export const GET_MUSIC_INFO = 'GET_MUSIC_INFO'
export const APPEND_MUSIC_INFO = 'APPEND_MUSIC_INFO'
export const NO_LEFT_MUSIC_INFO = 'NO_LEFT_MUSIC_INFO'
export const CHANGE_MUSIC_DETAIL_ID = 'CHANGE_MUSIC_DETAIL_ID'
export const SET_MUSIC_DETAIL = 'SET_MUSIC_DETAIL'

export const GET_MOVIE_INFO = 'GET_MOVIE_INFO'
export const APPEND_MOVIE_INFO = 'APPEND_MOVIE_INFO'
export const RESET_MOVIE_INFO = 'RESET_MOVIE_INFO'