export const GET_MUSIC_INFO = 'GET_MUSIC_INFO'
export const APPEND_MUSIC_INFO = 'APPEND_MUSIC_INFO'
export const CHANGE_MUSIC_DETAIL_ID = 'CHANGE_MUSIC_DETAIL_ID'
export const SET_MUSIC_DETAIL = 'SET_MUSIC_DETAIL'